### ISSUE TITLE
`PytestUnknownMarkWarning: Unknown pytest.mark.integration`

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/asf-tools#193]
Pytest complains about `PytestUnknownMarkWarning: Unknown pytest.mark.integration`. I wonder if we intended to include https://pypi.org/project/pytest-integration-mark/ as a dependency? Currently it is not included in https://github.com/ASFHyP3/asf-tools/blob/develop/environment.yml

**Comment by jhkennedy** [comment]
Ooh nice! This looks like a plugin to do exactly what we hacked together to specify integration tests.

**Comment by jtherrmann** [comment]
Unfortunately it depends on an older version of `pytest`: https://github.com/Barbora-Data-Science/pytest-integration-mark/blob/main/pyproject.toml#L20 which, on my machine, results in installing `pytest-6.2.5`, which causes an import error when attempting to run the tests:

```
  File "/home/jth/jth-apps/mambaforge/envs/equal-percent-solution/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 30, in <module>
    import py
ModuleNotFoundError: No module named 'py'
```

So we could open a PR to upgrade the `pytest` version pin in `pytest-integration-mark`.

**Comment by jhkennedy** [comment]
ugg, top pins. I *hate* poetry projects.
