### ISSUE TITLE
Missing Water Mask TIF file in the AWS S3 bucket

### ISSUE THREAD

**Issue by zxdawn** [ASFHyP3/asf-tools#239]
**Jira:** https://asfdaac.atlassian.net/browse/TOOL-2923

*Note: The above link is accessible only to members of ASF.*

----------------------------------------------------------------------------------------------------

Hi, I have checked the AWS bucket and found that there are three missing files:

```
s05w055.tif
s05w110.tif
s10w055.tif
```

Could you update the bucket to fix this problem?

**Comment by zxdawn** [comment]
Ha, thanks for the quick reply! Looking forward to the fix in the future ;)

**Comment by AndrewPlayer3** [comment]
All of the erroneous tiles should be fixed now.

<img width="1777" alt="image" src="https://github.com/user-attachments/assets/d580f08e-8c9d-4506-8d82-ec9f499bd4ea">

**Comment by zxdawn** [comment]
Thanks a lot! Everything works well now.
